debug: true
server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost/launchdb
    username: root
    password: r@th15hR
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
       ddl-auto: update

